import { Vehicle } from 'src/app/vehicle-list/vehicle';

export const VEHICLES: Vehicle[] = [
  { 
    id: 1, 
    name: 'BMW',
    img:'assets/images/1.jpg',
    type:'car',
    make:'toyota',
    model:'i8',
    mileage:'16.1 kmpl',
    price:'PKR 12.5 crore',
    year:'2019',
    color:'metal black',
    engine:'1500cc',
    rating:'4.2',
    loc:'Lahore',
    date:'01-02-2022',
    assembly:'imported',
    exterior:'32%',
    interior:'56%',
    transmission:'45%',
    stearing:'70%',
    suspension:'65%',
    seller_name:'Arshad Ali',
    seller_email:'arshad@gmail.com',
    seller_hrs:'09:00 AM to 07:00 PM',
    comments:'Wheels nd wheels inspected car <br> Inspection report atttched'
  },
  { 
    id: 2, 
    name: 'Mercedes',
    img:'assets/images/2.jpg',
    type:'car',
    make:'Mercedes',
    model:'Benz',
    mileage:'26.1 kmpl',
    price:'PKR 22.5 crore',
    year:'2021',
    color:'grey',
    engine:'1800cc',
    rating:'3.2',
    loc:'Karachi',
    date:'01-02-2022',
    assembly:'imported',
    exterior:'42%',
    interior:'66%',
    transmission:'55%',
    stearing:'100%',
    suspension:'75%',
    seller_name:'Feroz Khan',
    seller_email:'feroz@gmail.com',
    seller_hrs:'08:00 AM to 09:00 PM',
    comments:'Wheels nd wheels inspected car <br> Inspection report atttched'
   },
  { 
    id: 3, 
    name: 'Ferrari',
    img:'assets/images/3.jpg',
    type:'car',
    make:'Costruzioni',
    model:'3 Coupes',
    mileage:'18.9 kmpl',
    price:'PKR 10.5 crore',
    year:'2017',
    color:'deep red',
    engine:'1800cc',
    rating:'4.1',
    loc:'Islamabad',
    date:'01-02-2022',
    assembly:'imported',
    exterior:'22%',
    interior:'46%',
    transmission:'35%',
    stearing:'60%',
    suspension:'55%',
    seller_name:'Shams Illyas',
    seller_email:'shams@gmail.com',
    seller_hrs:'05:00 AM to 06:00 PM',
    comments:'Wheels nd wheels inspected car <br> Inspection report atttched'
  },
  { 
    id: 4, 
    name: 'Porsche',
    img:'assets/images/4.jpg',
    type:'car',
    make:'Costruzioni',
    model:'Cayman GT3',
    mileage:'20.9 kmpl',
    price:'PKR 14.5 crore',
    year:'2015',
    color:'yellow',
    engine:'1900cc',
    rating:'3.1',
    loc:'Islamabad',
    date:'01-02-2022',
    assembly:'imported',
    exterior:'29%',
    interior:'34%',
    transmission:'75%',
    stearing:'30%',
    suspension:'60%',
    seller_name:'Hassan Tahir',
    seller_email:'hassan@gmail.com',
    seller_hrs:'03:00 AM to 04:00 PM',
    comments:'Wheels nd wheels inspected car <br> Inspection report atttched'
  },
  { 
    id: 5, 
    name: 'BMW',
    img:'assets/images/5.jpg',
    type:'bike',
    make:'Costruzioni',
    model:'Cayman GT3',
    mileage:'20.9 kmpl',
    price:'PKR 14.5 crore',
    year:'2015',
    color:'yellow',
    engine:'1900cc',
    rating:'3.1',
    loc:'Islamabad',
    date:'01-02-2022',
    assembly:'imported',
    exterior:'50%',
    interior:'54%',
    transmission:'75%',
    stearing:'80%',
    suspension:'50%',
    seller_name:'Bilawal Bhutto',
    seller_email:'bhutt@gmail.com',
    seller_hrs:'06:00 AM to 11:00 AM',
    comments:'Wheels nd wheels inspected car <br> Inspection report atttched'
    
  },
  { 
    id: 6, 
    name: 'Kwasaki',
    img:'assets/images/6.jpg',
    type:'bike',
    make:'Volkswagen',
    model:'A8',
    mileage:'22.9 kmpl',
    price:'PKR 15.5 crore',
    year:'2019',
    color:'white',
    engine:'1700cc',
    rating:'4.8',
    loc:'Karachi',
    date:'01-02-2022',
    assembly:'imported',
    exterior:'69%',
    interior:'78%',
    transmission:'100%',
    stearing:'21%',
    suspension:'90%',
    seller_name:'Imran Khan',
    seller_email:'imran@gmail.com',
    seller_hrs:'07:00 PM to 08:00 PM',
    comments:'Wheels nd wheels inspected car <br> Inspection report atttched'
  },
  { 
    id: 7, 
    name: 'KTM',
    img:'assets/images/7.jpg',
    type:'bike',
    make:'Volkswagen',
    model:'A8',
    mileage:'22.9 kmpl',
    price:'PKR 15.5 crore',
    year:'2019',
    color:'white',
    engine:'1700cc',
    rating:'4.8',
    loc:'Faislabad',
    date:'01-02-2022',
    assembly:'imported',
    exterior:'29%',
    interior:'34%',
    transmission:'75%',
    stearing:'30%',
    suspension:'60%',
    seller_name:'Hassan Tahir',
    seller_email:'hassan@gmail.com',
    seller_hrs:'03:00 AM to 04:00 PM',
    comments:'Wheels nd wheels inspected car <br> Inspection report atttched'
  },
  { 
    id: 8, 
    name: 'Harley-Davidson',
    img:'assets/images/8.jpg',
    type:'bike',
    make:'Volkswagen',
    model:'A8',
    mileage:'22.9 kmpl',
    price:'PKR 15.5 crore',
    year:'2019',
    color:'white',
    engine:'1700cc',
    rating:'4.8',
    loc:'Peshawar',
    date:'11-06-2022',
    assembly:'imported',
    exterior:'80%',
    interior:'54%',
    transmission:'45%',
    stearing:'80%',
    suspension:'70%',
    seller_name:'Shahbaz Sharif',
    seller_email:'sharif@gmail.com',
    seller_hrs:'11:00 AM to 01:00 PM',
    comments:'Wheels nd wheels inspected car <br> Inspection report atttched'
  },
  { 
    id: 9, 
    name: 'Audi',
    img:'assets/images/9.jpg',
    type:'car',
    make:'Volkswagen',
    model:'A8',
    mileage:'22.9 kmpl',
    price:'PKR 15.5 crore',
    year:'2019',
    color:'white',
    engine:'1700cc',
    rating:'4.8',
    loc:'Karachi',
    date:'06-10-2022',
    assembly:'imported',
    exterior:'89%',
    interior:'56%',
    transmission:'65%',
    stearing:'50%',
    suspension:'70%',
    seller_name:'Saleem Ahmed',
    seller_email:'ahmed@gmail.com',
    seller_hrs:'02:00 PM to 04:00 PM',
    comments:'Wheels nd wheels inspected car <br> Inspection report atttched'
  }

];