import { Vehicle } from 'src/app/vehicle-list/vehicle';

export const VEHICLES: Vehicle[] = [
  { 
    id: 1, 
    name: 'BMW',
    img:'assets/images/1.jpg',
    type:'car',
    make:'toyota',
    model:'Big',
    mileage:16.1,
    price:10,
    year:'2019',
    color:'black',
    engine:'1500cc',
    rating:'3',
    loc:'Lahore',
    date:'01-02-2022',
    assembly:'imported',
    exterior:'32%',
    interior:'56%',
    transmission:'45%',
    stearing:'70%',
    suspension:'65%',
    seller_name:'Arshad Ali',
    seller_email:'arshad@gmail.com',
    seller_hrs:'09:00 AM to 07:00 PM',
    comments:'Color Polar white with beige leather interior\nExclusive Line interior\nExclusive Line exterior',
    name2:'i8'
  },
  { 
    id: 2, 
    name: 'Mercedes',
    img:'assets/images/2.jpg',
    type:'car',
    make:'Mercedes',
    model:'Big',
    mileage:14.5,
    price:6,
    year:'2020',
    color:'black',
    engine:'1800cc',
    rating:'5',
    loc:'Karachi',
    date:'01-02-2022',
    assembly:'imported',
    exterior:'42%',
    interior:'66%',
    transmission:'55%',
    stearing:'100%',
    suspension:'75%',
    seller_name:'Feroz Khan',
    seller_email:'feroz@gmail.com',
    seller_hrs:'08:00 AM to 09:00 PM',
    comments:'Panaromic sunroof\nActive park assist\nTire pressure monitor',
    name2:'Benz GLC'
   },
  { 
    id: 3, 
    name: 'Ferrari',
    img:'assets/images/3.jpg',
    type:'car',
    make:'Costruzioni',
    model:'High Priced',
    mileage:14.4,
    price:7.5,
    year:'2021',
    color:'red',
    engine:'1500cc',
    rating:'2',
    loc:'Islamabad',
    date:'01-02-2022',
    assembly:'imported',
    exterior:'22%',
    interior:'46%',
    transmission:'35%',
    stearing:'60%',
    suspension:'55%',
    seller_name:'Shams Illyas',
    seller_email:'shams@gmail.com',
    seller_hrs:'05:00 AM to 06:00 PM',
    comments:'Rear roller blinds\nAmbient Lights\nParking package',
    name2:'3 Coupes'
  },
  { 
    id: 4, 
    name: 'Porsche',
    img:'assets/images/4.jpg',
    type:'car',
    make:'Costruzioni',
    model:'High Priced',
    mileage:16.3,
    price:9,
    year:'2022',
    color:'yellow',
    engine:'1800cc',
    rating:'3',
    loc:'Islamabad',
    date:'01-02-2022',
    assembly:'imported',
    exterior:'29%',
    interior:'34%',
    transmission:'75%',
    stearing:'30%',
    suspension:'60%',
    seller_name:'Hassan Tahir',
    seller_email:'hassan@gmail.com',
    seller_hrs:'03:00 AM to 04:00 PM',
    comments:'Mirrors package\nShahnawaz import\nParking package',
    name2:'Cayman GT3'
  },
  { 
    id: 5, 
    name: 'BMW',
    img:'assets/images/5.jpg',
    type:'bike',
    make:'Costruzioni',
    model:'Family',
    mileage:10.2,
    price:5.5,
    year:'2019',
    color:'black',
    engine:'1300cc',
    rating:'1',
    loc:'Islamabad',
    date:'01-02-2022',
    assembly:'imported',
    exterior:'50%',
    interior:'54%',
    transmission:'75%',
    stearing:'80%',
    suspension:'50%',
    seller_name:'Bilawal Bhutto',
    seller_email:'bhutt@gmail.com',
    seller_hrs:'06:00 AM to 11:00 AM',
    comments:'Aftermarket Accessories\n    Quick shifter installed\nAkra full system installed',
    name2:'Cayman GT3'
    
  },
  { 
    id: 6, 
    name: 'Kwasaki',
    img:'assets/images/6.jpg',
    type:'bike',
    make:'Volkswagen',
    model:'High Priced',
    mileage:14.6,
    price:3,
    year:'2020',
    color:'black',
    engine:'1600cc',
    rating:'4',
    loc:'Karachi',
    date:'01-02-2022',
    assembly:'imported',
    exterior:'69%',
    interior:'78%',
    transmission:'100%',
    stearing:'21%',
    suspension:'90%',
    seller_name:'Imran Khan',
    seller_email:'imran@gmail.com',
    seller_hrs:'07:00 PM to 08:00 PM',
    comments:'Crash gardes installed\n    Total genuine\nOnly for serious buyers can call',
    name2:'Jet Ski'
  },
  { 
    id: 7, 
    name: 'KTM',
    img:'assets/images/7.jpg',
    type:'bike',
    make:'Volkswagen',
    model:'Big',
    mileage:10.2,
    price:2.5,
    year:'2021',
    color:'white',
    engine:'1600cc',
    rating:'4',
    loc:'Faislabad',
    date:'01-02-2022',
    assembly:'imported',
    exterior:'29%',
    interior:'34%',
    transmission:'75%',
    stearing:'30%',
    suspension:'60%',
    seller_name:'Hassan Tahir',
    seller_email:'hassan@gmail.com',
    seller_hrs:'03:00 AM to 04:00 PM',
    comments:'Exaust installed\nCrash gardes installed\nShorty levers installed',
    name2:'Travel Bike'
  },
  { 
    id: 8, 
    name: 'Harley-Davidson',
    img:'assets/images/8.jpg',
    type:'bike',
    make:'Volkswagen',
    model:'Big',
    mileage:8.8,
    price:4.5,
    year:'2022',
    color:'black',
    engine:'1300cc',
    rating:'5',
    loc:'Peshawar',
    date:'11-06-2022',
    assembly:'imported',
    exterior:'80%',
    interior:'54%',
    transmission:'45%',
    stearing:'80%',
    suspension:'70%',
    seller_name:'Shahbaz Sharif',
    seller_email:'sharif@gmail.com',
    seller_hrs:'11:00 AM to 01:00 PM',
    comments:'brand New tyres\nwheels sliders Front\ncrash guard\nyoshimur Alfa',
    name2:'Fat Bob'
  },
  { 
    id: 9, 
    name: 'Audi',
    img:'assets/images/9.jpg',
    type:'car',
    make:'Volkswagen',
    model:'Family',
    mileage:8.6,
    price:1.5,
    year:'2019',
    color:'white',
    engine:'1500cc',
    rating:'3',
    loc:'Karachi',
    date:'06-10-2022',
    assembly:'imported',
    exterior:'89%',
    interior:'56%',
    transmission:'65%',
    stearing:'50%',
    suspension:'70%',
    seller_name:'Saleem Ahmed',
    seller_email:'ahmed@gmail.com',
    seller_hrs:'02:00 PM to 04:00 PM',
    comments:'Yokohama tyres\nTinted windows\nLeather steering installed',
    name2:'Q5 Sportback'
  }

];